// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import "trix"
import "@rails/actiontext"
import "popper"
import "jquery"
import "jquery_ujs"
import "@rails/request.js"
import "bootstrap"
import "./admins/users_index"
import "./admins/change_status"
import "./users/user_change_anonymous"